import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const supabase = createClient(
  "https://hakhmatvjvjinkfeilbv.supabase.co", 
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhha2htYXR2anZqaW5rZmVpbGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxMTM5NDAsImV4cCI6MjA5NzY4OTk0MH0.sxbTw9-dvNTXh-Clog9BAAf6HjgNETNRki_vKe5vBCE"
);

const token = "eyJhbGciOiJFUzI1NiIsImtpZCI6ImY0NDAyMjE1LTA3YWMtNGNiZi04MjEwLWViNjRjMTgzNzc5ZCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2hha2htYXR2anZqaW5rZmVpbGJ2LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI1ZjdkNjRkMC05OTcxLTQ0NmEtOWUzMC0yOGZiZTg4OTcyNjUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgyNzk4NTIyLCJpYXQiOjE3ODI3OTQ5MjIsImVtYWlsIjoic3J2Z3VwdGEwMDdAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InNydmd1cHRhMDA3QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJTb3VyYXYgR3VwdGEiLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInJvbGUiOiJib3Jyb3dlciIsInN1YiI6IjVmN2Q2NGQwLTk5NzEtNDQ2YS05ZTMwLTI4ZmJlODg5NzI2NSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgyNzExNDYyfV0sInNlc3Npb25faWQiOiI5MzYxZjY3NC03MTA2LTRjZTktYWY4NC1iZDViOWZmY2YzMTkiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.0yx9U5_i9cr6SRYg6LSvr_eRiTEZFxo0iuuiXqQ8-2O-cmuyfG36kDuGBe3p7OUnHq3zqvcJgavOqoMMCeKPag";

async function run() {
  const { data, error } = await supabase.auth.getUser(token);
  console.log("getUser(token) Error:", error?.message);
}
run();
